services:
  api:
    container_name: billing_system
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - api
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
 api:
volumes:
 pgdata: